server:
  port: 8768
spring:
  application:
    name: ribbon-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/

#ribbon:
#  eureka:
#    enabled: false
#
#eureka-client:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: localhost:8764,localhost:8765

